// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/12/2026, 6:19:12 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/a1111/PhpstormProjects/my-orders/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/a1111/PhpstormProjects/my-orders/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/a1111/PhpstormProjects/my-orders/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/a1111/PhpstormProjects/my-orders/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/a1111/PhpstormProjects/my-orders/plugins/**/*.{js,ts,mjs}","/Users/a1111/PhpstormProjects/my-orders/composables/**/*.{js,ts,mjs}","/Users/a1111/PhpstormProjects/my-orders/utils/**/*.{js,ts,mjs}","/Users/a1111/PhpstormProjects/my-orders/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/a1111/PhpstormProjects/my-orders/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/a1111/PhpstormProjects/my-orders/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;